spring:
  application:
    name: book
  ai:
    ollama:
      base-url: 'http://192.168.1.3:11434'

server:
  port: 8080
local:
  voice-model-dir: E:\\work\\story-maker\\CosyVoice\\voice.py
  server-dir: E:\\work\\story-maker\\CosyVoice\\server.py
  python-dir: C:\\ProgramData\\miniconda3\\envs\\cosyvoice\\python.exe
  remote-python: http://192.168.1.3:8000